#!/usr/bin/env sh

# Loads all defined colors
source "$HOME/.config/sketchybar/utils/colors.sh" 
# Loads all defined icons
source "$HOME/.config/sketchybar/utils/icons.sh" 
# Loads all the defined dimensions
source "$HOME/.config/sketchybar/utils/appearance.sh"

# Directory where the items are configured
ITEM_DIR="$HOME/.config/sketchybar/items" 

# Directory where all the plugin scripts are stored
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" 

# Needs to have Regular, Bold, Semibold, Heavy and Black variants
FONT=$BAR_FONT 
# The script that is run for clicking on space components
SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" 


POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11


# Setting up the general bar appearance and default values
sketchybar --bar     height=$BAR_HEIGHT                                 \
                     color=$BAR_COLOR                                   \
                     shadow=$SHADOW                                     \
                     position=$BAR_POSITION                             \
                     sticky=$BAR_STICKY                                 \
                     padding_right=$PADDING_RIGHT                       \
                     padding_left=$PADDING_LEFT                         \
                     corner_radius=$BAR_CORNER_RADIOUS                  \
                     y_offset=$BAR_Y_OFFSET                             \
                     margin=$BAR_MARGIN                                 \
                     blur_radius=$BAR_BLUR                                     \
                     topmost=$BAR_TOPMOST                               \
                                                                        \
           --default updates=when_shown                                 \
                     icon.font="$FONT:Bold:14.0"                        \
                     icon.color=$ICON_COLOR                             \
                     icon.padding_left=$PADDINGS                        \
                     icon.padding_right=$PADDINGS                       \
                     label.font="$FONT:Semibold:13.0"                   \
                     label.color=$LABEL_COLOR                           \
                     label.padding_left=$PADDINGS                       \
                     label.padding_right=$PADDINGS                      \
                     background.padding_right=$PADDINGS                 \
                     background.padding_left=$PADDINGS                  \
                     popup.background.border_width=2                    \
                     popup.background.corner_radius=11                  \
                     popup.background.border_color=$POPUP_BORDER_COLOR  \
                     popup.background.color=$POPUP_BACKGROUND_COLOR     \
                     popup.background.shadow.drawing=$SHADOW

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"

# Center

############## FINALIZING THE SETUP ##############
sketchybar --update

echo "sketchybar configuation loaded.."
